### ISSUE TITLE
The error class and tooltip can not be removed on valid when it's empty

### ISSUE THREAD

**Issue by mirari** [Thrilleratplay/jquery-validation-bootstrap-tooltip#10]
successList does not include those empty inputs.
Example:
			"email-edit" : {
				email : true
			}
This input is optional.
It shows error when I input a wrong email address,but when I delete my input,the error info is still there.
So I think the "defaultShowErrors" method should be like this:
$.each(this.successList, function(index, value) {
...
});

change to:

$.each(this.validElements(), function(index, value) {
...
});

**Comment by Thrilleratplay** [comment]
I'm going to have to agree with you.  After taking a look at the jQuery validation source and open issues, you may have solved a number of open issues with vague descriptions that sound just like this.  

When I have free time later tonight, I will to do more investigating and testing to ensure this fix does not break anything else.

**Comment by Thrilleratplay** [comment]
Hmmm.  This is going to be more work than I originally though.  Sorry, I'll try to have a fix in the next day or two.

**Comment by Thrilleratplay** [comment]
I was making it more complicated than it actually was.  You were right.  I pushed the fix.
