### ISSUE TITLE
jquery-validation-bootstrap-tooltip placement right does not work with _all_

### ISSUE THREAD

**Issue by swamyuma** [Thrilleratplay/jquery-validation-bootstrap-tooltip#11]
Thanks for creating a very useful plugin.  With the `_all_` option, only default placement 'top' works. It displays the tooltip always at the top, even after changing the placement to 'right' (or anything other than 'top').  Below is a snippet of what I have in my code.
```javascript 
tooltip_options:{
            '_all_': {placement: 'right'},
        },
```

**Comment by Thrilleratplay** [comment]
Here is a fiddle with the snippet provided: http://jsfiddle.net/thrilleratplay/uhd7qgq8/1/

In both Firefox and Chromium, it works with the caveat that the tooltips were not rendering correctly if there was not enough space.  

Try double checking the element selector

**Comment by swamyuma** [comment]
I was using the `flicker` version and when I switched to the `jquery-validate.bootstrap-tooltip.min.js` version, placement right is working. Thanks!
