### ISSUE TITLE
not issue but question: update tooltips and messages after ajax submit

### ISSUE THREAD

**Issue by xenogenesi** [Thrilleratplay/jquery-validation-bootstrap-tooltip#12]
First, nice work!

I'd like to use it but I'd like to integrate server side ajax/php validation, is there a way to update fields with errors and error messages with the content of returning json?
(I'm looking into it but I was hoping you can save me some time)

**Comment by Thrilleratplay** [comment]
Without knowing specifics, I am going to say yes.  

This is nothing more than a simple bridge between Bootstrap's tooltip component and jQuery Validation.  Examples of custom messages, weather they be text or HTML, are included in the demos.  While I have not tried to dynamically define messages, you should be able.  Depending on implmenetation, the jQuery Validation's validation() method may have to be reinitialized with the returned parsed JSON.

Again, this is not knowing the specifics.  If the server is doing the validation and returning a unique error message, you may want to take a look at http://jqueryvalidation.org/remote-method/.  I would assume it would work with this plugin but have not tested it to be 100% sure.

**Comment by xenogenesi** [comment]
Thank you very much @Thrilleratplay, I had some further thought about, keeping a double (js/php) validation synced is looking for troubles, php is mandatory, so I'm (sadly, because can't find anything ready to use) writing the thing from scratch, dummy js which just submit via ajax on rate-limited events the whole form, and fill the bs's tooltips (highly inspired by your plugin) with the json response. Cheers
