### ISSUE TITLE
Chosen

### ISSUE THREAD

**Issue by p34eu** [Thrilleratplay/jquery-validation-bootstrap-tooltip#14]
Great idea but  it breaks validation on chosen select. Does not show messages and skip's adding the error class.

**Comment by Thrilleratplay** [comment]
It is working in this example:  http://jsfiddle.net/thrilleratplay/sb4pjgoc/1/

Is your select element required?

**Comment by p34eu** [comment]
Yes. 

It breaks when using "Chosen select" https://harvesthq.github.io/chosen/ with the  select element.

http://jsfiddle.net/m23znjpn/1/

**Comment by Thrilleratplay** [comment]
This project is a bridge between jQuery Validation and Bootstrap's Tooltip plugins.  Harvesthq's Chosen has a custom stylesheet but Github has a few projects where other developers have added Bootstrap styling, [here is an example](https://github.com/alxlit/bootstrap-chosen).  I have a feeling the problem you are running into is related to an few open issues in Chosen regarding jQuery validation.  [Someone has posted a work around here](https://github.com/harvesthq/chosen/issues/473).  

I hope the work around fixes your issue but Chosen is outside of the scope of this project and not officially supported.

**Comment by p34eu** [comment]
Thanks, Thrilleratplay, 
Indeed, $.validator.setDefaults({ ignore: ":hidden:not(select)" } makes Chosen work also with your tooltips plugin.
