### ISSUE TITLE
Object key "_all_" not working

### ISSUE THREAD

**Issue by pauldowlin** [Thrilleratplay/jquery-validation-bootstrap-tooltip#16]
Using input name works but when I switch to the `_all_` object it uses defaults.  Is this just me?

```
$("#simple-c1").validate({
     tooltip_options: {
          "_all_": { placement: 'right' }
     }
});
```

I'm calling version 1.9.1 of jquery (was using 1.11.3 but saw you were using 1.9.1 on demo page) from google as well as latest jquery validate & bootstrap. I'm also using jquery-validate.bootstrap-tooltip.flickerfix

**Comment by pauldowlin** [comment]
I should learn to cover my bases first before commenting!

flickerfix version is missing `_` surrounding `all`.

**Comment by Thrilleratplay** [comment]
Thanks for pointing that out and sorry for any inconvenience.  Fix has been pushed.
