### ISSUE TITLE
v4.0.0-Alpha - Destroy is now Dispose

### ISSUE THREAD

**Issue by patrickgatesconsulting** [Thrilleratplay/jquery-validation-bootstrap-tooltip#17]
The method "destroy" nolonger works with Bootstrap V4.0.0-alpha, it is now dispose. It causes a bug on tooltip update.

https://github.com/twbs/bootstrap/issues/17544

**Comment by Thrilleratplay** [comment]
I have not been keeping up with alpha development.  Thank you for not only pointing out but also the cause and solution to this bug as the Bootstrap documentation has still not been updated to reflect this.  I apologize for the delay, as there are now three major Bootstrap versions I want to support I had to do some house cleaning.

v0.10.0 will work for Bootstrap v2, v3 and v4 or until they make another change in alpha development.
