### ISSUE TITLE
jQuery dependency version

### ISSUE THREAD

**Issue by Shaazaam** [Thrilleratplay/jquery-validation-bootstrap-tooltip#18]
I took a peek at your package.json and noticed your jQuery dependency version is ~1.10 and I think my npm-update is failing on this. Npm seems to think its asking for jquery@'>=1.10.0 <1.11.0' (which is what ~1.10 means I think).

Removing your library solves the problem. https://docs.npmjs.com/misc/semver#Ranges explains all of the ranges and whatnot. I may be wrong, but setting it to >=1.10 should solve this issue.

**Comment by Thrilleratplay** [comment]
You are correct.  I meant to use the caret instead of the tilde.  The package.json and bower.json files have been updated.  Thank you for pointing that out.

**Comment by Shaazaam** [comment]
Thank you for getting to this as quick as you did. Everything is working great now and your plugin fits well with my system. Good job, and keep up the work!
