### ISSUE TITLE
Apply tooltips only to certain forms

### ISSUE THREAD

**Issue by chrisvogt** [Thrilleratplay/jquery-validation-bootstrap-tooltip#22]
Is it possible to target which instances of `.validate()` this is applied to?

Example: I have a collection of forms using the validation plugin, but only some I want tooltips on — the rest should revert to their default behavior, which allows me to define my own `errorLabelContainer`, `errorElement`, etc.

**Comment by Thrilleratplay** [comment]
Hmmm.  I never thought about doing a mixture.

As is, I am going to have to say no.  This plugin works by extending the [defaultShowErrors function](https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L839) in jQuery-validate and replacing the default functionality.  

My suggestion would be to fork this project and splice together the original error labels and tooltips based on some criteria of the element's.

**Comment by chrisvogt** [comment]
Thanks! I looked into it, and have achieved what I wanted by hacking both this project and [jquery-validation](https://github.com/jzaefferer/jquery-validation) the following way:

_jquery-validate.bootstrap-tooltip.js_
* Renamed `defaultShowErrors()` to `tooltipShowErrors()`.

_jquery.validate.js — showErrors()_
```js
if ( this.settings.showErrors ) {
    if ( this.settings.showErrors === 'tooltips' ) {
        this.tooltipShowErrors();
    } else {
        this.settings.showErrors.call( this, this.errorMap, this.errorList );
    }
} else {
    this.defaultShowErrors();
}
```

Now, I can switch between the two per form by adding the setting `showErrors: null` or `showErrors: tooltips`.

There may be a less hackish way to do this utilizing the plugin code that is already there, because it appears [that setting](http://jqueryvalidation.org/Validator.showErrors) calls a function and passes a list of errors.

**Comment by Thrilleratplay** [comment]
That is more or less how I was thinking about doing it.  Sorry there was isn't a more elegant way.
