### ISSUE TITLE
jquery.validate-1.14.0.min.js MISSING in ZIP

### ISSUE THREAD

**Issue by XanderCam** [Thrilleratplay/jquery-validation-bootstrap-tooltip#24]
I scratched my head for a few minutes when I couldn't get your project to work locally.
Then after checking your example sourcecode, I found that you have not included: "jquery.validate-1.14.0.min.js" into your git.

**Comment by Thrilleratplay** [comment]
This is intentional.  The master branch contains only the files for this project.  As jQuery, jQuery Validate and Twitter Bootstrap are required dependencies, it is expected they are add independently so you can use which ever versions your project warrants.
