### ISSUE TITLE
Disable tooltips for a certain (hidden) field.

### ISSUE THREAD

**Issue by mitsest** [Thrilleratplay/jquery-validation-bootstrap-tooltip#25]
Hi,
Thanks for your plugin!

I was wondering if there is a way of disabling tooltips for a field.
If you want to know more about my case it's about a textarea that gets hidden because I'm using tinyMCE editor. So, because it gets hidden, the tooltip does not appear where it's supposed to.

So I want to rollback to the default validation error for this field only.
Is there a way to achieve this?

I tried 
```javascript
.validate({
      tooltip_options: {
        textarea: null
      },
```
but no luck.

Thanks!

**Comment by mitsest** [comment]
I ended up amending your override of defaultShowErrors like this (note: the website I 'm working on uses bootstrap 2):
```javascript
            if ($(value.element).is(':visible')) {
              $(value.element).removeClass(_this.settings.validClass)
                              .addClass(_this.settings.errorClass)
                              .tooltip(bsMajorVer === 4 ? 'dispose' : 'destroy')
                              .tooltip(_this.applyTooltipOptions(value.element, value.message))
                              .tooltip('show');
            } else {
              _this.showLabel( value.element, value.message );
            }
```

**Comment by Thrilleratplay** [comment]
I would not suggest this approach as there are a few ways to override this behavior in jquery-validation.  If this hidden field is not required, as in can be empty, try the `ignore` property.

```JavaScript
.validate({
  ignore: ':hidden'
})
```

I am also guessing the site is using an older version of jquery-validation because ignoring hidden fields was a default added to version 1.9.

**Comment by mitsest** [comment]
Hey, thanks for the fast reply.
Nah, I 'm afraid it is required, as tinyMCE on save, fills up this textarea and then the validation kicks in.

I 've added ignore: "" for this.

**Comment by Thrilleratplay** [comment]
Damn, it is never the easy answer.  I was going to suggest `errorPlacement` however this is not called when using this plugin.  Unfortunately, I think you have to use the work around you have in place for the time being.  If I get time, I will try to create a formal solution to this later today.

**Comment by mitsest** [comment]
Allright.
Thanks again for your time :)

**Comment by Thrilleratplay** [comment]
I did some investigating.  For a plain hidden required textarea using Bootstrap v2.3.2, I could not get a tooltip error to display for that element.  Based on a few StackOverflow answers, it looks like different versions TinyMCE have quirks that could be causing your issue.  If the code you posted works for you, then user it.  The other work around looks like handling validation through the TinyMCE API instead of HTML5.

**Comment by mitsest** [comment]
hmmm, in my case it got displayed at the far left edge of the screen...(maybe something to do with display: none positioning?)

**Comment by Jaded-Design** [comment]
I'll open another issue since i hate just adding on to a closed issue but did you guys ever come up with a solution for this? I've got hidden inputs that are holding the values for Select2 select boxes and while I am able to validate the hidden inputs, the tooltips for all the select boxes are just piling up on the left side of the screen... 

Is there a way to validate, but not throw an error message for certain hidden fields?

**Comment by Thrilleratplay** [comment]
@Jaded-Design I did not find a built in way to validate a field that does not display an error.  This makes sense in theory but there are these kinds of edge cases.  To do this, you will likely need to fork this project and make modifications to fit your needs.

Looking at [the examples](https://select2.github.io/examples.html), I would think that the if the select element had the `select2-hidden-accessible` class, tooltips errors would appear relatively close to the visible selector element.  If you want to put together a jsfiddle example, I can take a look at it later.  Now, you are using the standard Select2.js library and not the Angular-UI or other custom version, correct?

**Comment by Jaded-Design** [comment]
For others that are running in to this issue, what I ended up doing was using CSS display:none on the tooltips for this particular form and then used the validation summary and highlighting of the inputs to show users what needed to be corrected. 

So using the invalidHandler you do the following: 
```
    invalidHandler: function (form, validator) {
                    $(".validation_summary").html('<div class="alert alert-warning validation-warnings">You have ' + validator.numberOfInvalids() + ' error' + (validator.numberOfInvalids() > 1 ? 's' : '') + ' in the form.  Please correct the following: <ul class="validationsummarybox"></ul></div>');
                    for (var prop in validator.invalid) {
                        if (validator.invalid.hasOwnProperty(prop)) {
                            $(".validationsummarybox").append("<li class='validationprobs'>" + validator.invalid[prop] + "</span>")

                        }
                    }
                },
```
Then on your form (I put it on top AND bottom) you insert this html: 
`                                <div class="validation_summary"></div>
`

**Comment by Jaded-Design** [comment]
@Thrilleratplay Yes, I am just using the standard Select2.js version 4.0

Don't spend any time on this for my sake though as I have already punted the idea of using the tooltips for this particular form and will just go ahead with summary and highlighting of the select2s. 

Luckily it's an internal app so no customers have to use it and our salesman can just fill out the form correctly the first time :) 

Thanks for taking a look at this though. Digging the library.

**Comment by Thrilleratplay** [comment]
commenting in #27
