### ISSUE TITLE
Add pretty form validation display

### ISSUE THREAD

**Issue by mjenczmyk** [Thrilleratplay/jquery-validation-bootstrap-tooltip#26]
Hello everyone!

Recently I wrote [such script](https://gist.github.com/mjenczmyk/8c2fbdb66579a5040fc58023c4001a95) to improve the way I display form input state in templates in my Django project. Basically it adds `has-error`/`has-success` class to `form-group` wrapping inputs and adds `form-control-feedback` icon to input. I use it with jQuery Validator and this plugin.

Would you be interested in embedding such features into your plugin? I'm a JS newbie, but I can try to prepare pull request adding:
* `has-error`/`has-success` class to `form-group` on validation,
* displaying `form-control-feedback` icon at input,

with some settings turning on/off these features in the plugin.

It's partially based on [DARK_DIESEL post](http://stackoverflow.com/a/24826314).

**Comment by Thrilleratplay** [comment]
Thank you, but I would prefer to keep this plugin as simple and generic as possible.  It would be damn near impossible to support every additional framework or jQuery plugin, then each version of those, without introducing bugs or increase the size.  

You are more than welcome to fork the project and make the modification specific to your script.

**Comment by mjenczmyk** [comment]
OK, I see. Have a good day!
