### ISSUE TITLE
Validate Hidden Inputs, But Don't Display Error Tooltips

### ISSUE THREAD

**Issue by Jaded-Design** [Thrilleratplay/jquery-validation-bootstrap-tooltip#27]
I've got hidden inputs that are holding the values for Select2 select boxes and while I am able to validate the hidden inputs, the tooltips for all the select boxes are just piling up on the left side of the screen...

I'd like to be able to still validate the hidden inputs but without showing a tooltip if there is an error. Alternatively, if there is a way to attach the tooltip error to the select2 box, that would be ideal.

**Comment by Jaded-Design** [comment]
For others that are running in to this issue, what I ended up doing was using CSS display:none on the tooltips for this particular form and then used the validation summary and highlighting of the inputs to show users what needed to be corrected. 

So using the invalidHandler you do the following: 
```
    invalidHandler: function (form, validator) {
                    $(".validation_summary").html('<div class="alert alert-warning validation-warnings">You have ' + validator.numberOfInvalids() + ' error' + (validator.numberOfInvalids() > 1 ? 's' : '') + ' in the form.  Please correct the following: <ul class="validationsummarybox"></ul></div>');
                    for (var prop in validator.invalid) {
                        if (validator.invalid.hasOwnProperty(prop)) {
                            $(".validationsummarybox").append("<li class='validationprobs'>" + validator.invalid[prop] + "</span>")

                        }
                    }
                },
```
Then on your form (I put it on top AND bottom) you insert this html: 
`                                <div class="validation_summary"></div>
`

**Comment by Thrilleratplay** [comment]
@Jaded-Design OK, glad you found a work around.  If you change your mind, just create a JSFiddle example of the issue and reopen this ticket.
