### ISSUE TITLE
Valid input radio or checkbox if it's hidden

### ISSUE THREAD

**Issue by tomtopweb** [Thrilleratplay/jquery-validation-bootstrap-tooltip#28]
When I using the validation with input[type=checkbox] { display:none; }  
because on front-end I'm showing the selected one by label and css, then the tooltip it's not appering and the validation is not working.

**Comment by Thrilleratplay** [comment]
This is likely due to [jQuery Validation ignoring hidden and disabled fields by default](https://jqueryvalidation.org/validate/).  You can override this behavior to validate the fields but this may cause the tooltip to appear elsewhere on the page.

**Comment by Thrilleratplay** [comment]
Closing issue, pending a response.

@tomtopweb If this is not the solution to your problem, please reopen and post a JSFiddle demoing the issue.
