### ISSUE TITLE
not override resetForm function ...

### ISSUE THREAD

**Issue by jast90** [Thrilleratplay/jquery-validation-bootstrap-tooltip#29]
not override [resetForm](https://jqueryvalidation.org/Validator.resetForm/) function .So in some condition not work.The condition is I have a bootstrap Modal show valid fields ,when valid fields show error message  and hide the modal  at the same time ,but when I show the modal again the fail message was showed.

**Comment by Thrilleratplay** [comment]
Can you provide a [jsFiddle](https://jsfiddle.net/) as an example of how this does not in some conditions?

**Comment by jast90** [comment]
@Thrilleratplay updated

**Comment by Thrilleratplay** [comment]
Consolidating into #30
