### ISSUE TITLE
Set default placement for entire form

### ISSUE THREAD

**Issue by michaeldevenney** [Thrilleratplay/jquery-validation-bootstrap-tooltip#31]
Is it possible to set a default for tooltip placement for the entire form instead of going element by element?

**Comment by Thrilleratplay** [comment]
@michaeldevenney Yes, instead of specifying the individual element names under `tooltip_options`, you can use `_all_`

**Comment by michaeldevenney** [comment]
Awesome, works like a charm!  Thanks!
