### ISSUE TITLE
how to conform password

### ISSUE THREAD

**Issue by fazalsandhi** [Thrilleratplay/jquery-validation-bootstrap-tooltip#32]
how to check confirm password

**Comment by Thrilleratplay** [comment]
All validation is handled by [jQuery-Validation](https://jqueryvalidation.org).  This plugin only changes the error messages from labels to Bootstrap tooltips.  If you only want to check if a field is populated, then make it required.

**Comment by fazalsandhi** [comment]
no i mean validate password and confirm password what i mean is

**Comment by fazalsandhi** [comment]
ok thanks
