### ISSUE TITLE
Using with label :before or :after css

### ISSUE THREAD

**Issue by tomtopweb** [Thrilleratplay/jquery-validation-bootstrap-tooltip#33]
When using radio or checkbox input elements with hidden input and using :after css for showing FontAwsome icons to see the status of the elements after submiting the form it removes the :after from the label after my inputs.

So this is what I have:
```
**<input type="radio" name="using_type"  id="input01" required="true" >
<label class="label-radio" for="input01">
::before
input01</label>**
```

and after when it shows the tooltip for the error of validating, the :after css gone from the code, it seems it's refreshing that area.

```
**<input type="radio" name="using_type"  id="input01" required="true" >
<div class="tooltip fade top in" role="tooltip" id="tooltip432339" style="top: -43px; left: -58.5px; display: block;"><div class="tooltip-arrow" style="left: 50%;"></div><div class="tooltip-inner">Message</div></div>
<label class="label-radio" for="input01">input01</label>**
```

Any idea how to fix this? Thank you!!

**Comment by Thrilleratplay** [comment]
```
**<input type="radio" name="using_type"  id="input01" required="true" >
<label class="label-radio" for="input01">
::before
input01</label>**
```
Is that the final HTML that is rendered?  No processing or templating engines that would modify this afterwards?  I have never seen the `::before` CSS pseudo element placed in HTML like that.  

Could you also include the CSS you have that binds the icon to the label element?

**Comment by tomtopweb** [comment]
I'm using with this CSS

`input[type=radio] {  
   border: 0; 
  clip: rect(0 0 0 0); 
  height: 1px; margin: -1px; 
  overflow: hidden; 
  padding: 0; 
  position: absolute; 
  width: 1px;
}
input[type=radio] + label:before {
    position: absolute;
    font-family: FontAwesome;
    display: inline-block;
    background: #fff;
    width: 24px;
    line-height: 20px;
    height: 24px;
    border-radius: 20px;
    text-align: center;
    font-size: 10px;
    left: 0;
    overflow:visible !important;
}

input[type=radio] + label:before { content: "\f00c";border: solid 1px #cccccc;color: #fff;-moz-transition:all 0.2s ease-in-out; -webkit-transition:all 0.2s ease-in-out;}
input[type=radio]:checked + label:before { content: "\f00c";color: #fff ;border: solid 1px #4e8954 ;background: #57995e;-moz-transition:all 0.2s ease-in-out; -webkit-transition:all 0.2s ease-in-out;}`

**Comment by Thrilleratplay** [comment]
Ahhhh.... the `+` is [adjacent sibling selector](http://devdocs.io/css/adjacent_sibling_selectors).  As soon as the tooltip element is placed in between them, they are no longer adjacent.  The quick fix should be to use the [general sibling selector](http://devdocs.io/css/general_sibling_selectors) `~`.  However, depending on how many other sibling input and label elements there will be, it may be easier to use a separate element for the icon like the [Font Awesome example](http://fontawesome.io/examples/).

**Comment by tomtopweb** [comment]
Ohh, thank you very much! It solved the problem!

**Comment by Thrilleratplay** [comment]
No prob.  Happy to help.
