### ISSUE TITLE
Uncaught TypeError: Cannot read property 'animation' of undefined

### ISSUE THREAD

**Issue by Stone-Ynn** [Thrilleratplay/jquery-validation-bootstrap-tooltip#36]
the version: 
jquery 3.x 
bootstrap3.x 
jquery validate 0.5.2

 
<script type="text/javascript" src="/lib/jquery/jquery-3.1.0.min.js"></script>
<script type="text/javascript" src="/lib/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/lib/validate/jquery.validate.min.js"></script>
<script type="text/javascript" src="/lib/validate/localization/messages_zh.js"></script>
<script type="text/javascript" src="/lib/jquery-validation-bootstrap-tooltip/jquery-validate.bootstrap-tooltip.min.js"></script></head>

while i fllow the tutorial,  caused the error：
Uncaught TypeError: Cannot read property 'animation' of undefined

**Comment by Thrilleratplay** [comment]
Can you create a [JsFiddle](jsfiddle.net) reproducing this issue?

**Comment by Stone-Ynn** [comment]
@Thrilleratplay 

```
jquery-validate.bootstrap-tooltip.min.js:11 Uncaught TypeError: Cannot read property 'animation' of undefined
    at a.validator.applyTooltipOptions (jquery-validate.bootstrap-tooltip.min.js:11)
    at Object.<anonymous> (jquery-validate.bootstrap-tooltip.min.js:11)
    at Function.each (jquery-3.1.0.min.js:2)
    at a.validator.defaultShowErrors (jquery-validate.bootstrap-tooltip.min.js:11)
    at a.validator.showErrors (jquery.validate.min.js:4)
    at a.validator.form (jquery.validate.min.js:4)
    at HTMLFormElement.<anonymous> (jquery.validate.min.js:4)
    at HTMLFormElement.dispatch (jquery-3.1.0.min.js:3)
    at HTMLFormElement.q.handle (jquery-3.1.0.min.js:3)
applyTooltipOptions @ jquery-validate.bootstrap-tooltip.min.js:11
(anonymous) @ jquery-validate.bootstrap-tooltip.min.js:11
each @ jquery-3.1.0.min.js:2
defaultShowErrors @ jquery-validate.bootstrap-tooltip.min.js:11
showErrors @ jquery.validate.min.js:4
form @ jquery.validate.min.js:4
(anonymous) @ jquery.validate.min.js:4
dispatch @ jquery-3.1.0.min.js:3
q.handle @ jquery-3.1.0.min.js:3
```

**Comment by Thrilleratplay** [comment]
@Stone-Ynn Unfortunately, the error message alone does not provide enough information.   This issue is caused by an invalid element being passed into the `applyTooltipOptions` function but without seeing the implementation I cannot help.

**Comment by Stone-Ynn** [comment]
@Thrilleratplay OK, Thanks. But can you give me a complete demo. 
 I just reference the https://thrilleratplay.github.io/jquery-validation-bootstrap-tooltip/, and it don't work.

**Comment by Thrilleratplay** [comment]
@Stone-Ynn I'm sorry, I don't understand.  Are you saying the demos on https://thrilleratplay.github.io/jquery-validation-bootstrap-tooltip/ are not working?  They work when I try them.  

There are multiple possible causes that would create that error such as incompatible JQuery, JQuery-Validate and/or Bootstrap versions, HTML or JS syntax error, run time issue or something else.  Due to these variables, to assist, I need a working copy of your implementation that demonstrates this error.  I cannot reproduce this error with the information provided.

**Comment by Stone-Ynn** [comment]
@Thrilleratplay ok, i will try the other version of libs according to your demo. Expect to solve this issue. 
 Thanks for your reply anyway!

**Comment by Stone-Ynn** [comment]
@Thrilleratplay I solve the issue. the bootstrap version must be 3.3.5+ . then it works.

**Comment by Thrilleratplay** [comment]
@Stone-Ynn I'm glad you solved it.  Which version of Bootstrap were you using?

**Comment by Stone-Ynn** [comment]
@Thrilleratplay  Now i used the latest bootstrap V3.3.7 . 
And V3.3.1 caused that error.

**Comment by Thrilleratplay** [comment]
@Stone-Ynn Ahhh.  That was the missing piece of information.  [Jquery 3 was not compatible with Bootstrap until version 3.37](https://github.com/twbs/bootstrap/issues/16834).
