### ISSUE TITLE
Why jQuery v1.12.4?

### ISSUE THREAD

**Issue by Mina-R-Meshriky** [Thrilleratplay/jquery-validation-bootstrap-tooltip#43]
when installing using npm, the console gave me the following error, and by looking into the node module files I find that the library uses jquery v1.12.4 as a dependency
![image](https://user-images.githubusercontent.com/26849271/52060737-81c3b980-2575-11e9-9e2e-0a1c014518f5.png)

![image](https://user-images.githubusercontent.com/26849271/52060850-c8b1af00-2575-11e9-9742-557f8ce326de.png)

**Comment by Thrilleratplay** [comment]
It looks like the package.json was updated but not the npm module.  Sorry about that, I will update it later tonight.  The current dependency was updated to jquery: "^3.0.0" so you can manually update it in the meantime without any issue.

**Comment by Thrilleratplay** [comment]
Npm has been updated.
